name: Build Geode Mod
on: [push, workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        config:
          - name: Android
            os: ubuntu-latest
    runs-on: ${{ matrix.config.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Build Geode Mod
        uses: geode-sdk/build-geode-mod@main
        with:
          sdk: v3.0.0-beta.1
          target: Android64
          combine: true

